all:
	 g++ -std=c++11 -I. -o fumadores fumadores.cpp HoareMonitor.cpp -pthread
	 g++ -std=c++11 -I. -o barberia barberia.cpp HoareMonitor.cpp -pthread         
clean :
	rm salida fumadores barberia *~ \#* 2> /dev/null
